### ISSUE TITLE
Using asyncairtable in a netlify function 

### ISSUE THREAD

**Issue by cfab** [GV14982/async-airtable#82]
An example of a netlify function using your library would be welcome. Not sure why but I always end up with an error saying that "SyntaxError: Cannot use import statement outside a module"
And this happens wether I use the require or import syntax...
Here is an example code: 
```js
// import { AsyncAirtable } from 'asyncairtable';
const AsyncAirtable = require('asyncairtable');

const keys = {
  atApiKey: process.env.AT_API_KEY,
  atDb: process.env.AT_DB,
}
const asyncAirtable = new AsyncAirtable(keys.atApiKey, keys.atDb);

async function getMoviesWithRelatedAsyncAirtable() {
  
  const movies = await asyncAirtable.select('Movies')
  const formattedMovies = formatData(movies);
 
  formattedMovies.forEach(async (movie) => {
    movie.DirectorFull = await getDirector(movie.Director[0]);
    if (movie && movie.Actors) {
      movie.ActorsFull = await getActors(movie.Actors);
    }
  })
  return formattedMovies;
}

async function getDirector(directorId) {
  const director = await asyncAirtable.find('Directors', directorId)
  return director.fields;
}

function getActors(actorsIds) {
  const actors = []
  actorsIds.forEach(async (actorId) => {
    const actor = await asyncAirtable.find('Actors', actorId)
    actors.push(actor.fields)
  })
  return actors;
}

function formatData(data) {
  return data.map(item => ({
    id: item.id,
    ...item.fields
  }))
}

// The actual netlify function !
exports.handler = async (event, context) => {
  try {
    const movies = await getMoviesWithRelatedAsyncAirtable();
    return {
      statusCode: 200,
      body: JSON.stringify(movies),
    };
  } catch (err) {
    console.log(err);
    return {
      statusCode: 500,
      body: JSON.stringify(err),
    };
  }
}

```

**Comment by cfab** [comment]
Oh, I haven't seen this: https://www.netlify.com/blog/2021/04/02/modern-faster-netlify-functions/
so I dit it but now I got the following error: 
```
Request from ::1: GET /.netlify/functions/movies2
Error: Error: Error: TypeError: fetch_default is not a function
    at AsyncAirtable.<anonymous> (/Users/f/Sites/sister/node_modules/asyncairtable/src/asyncAirtable.ts:157:13)
    at Generator.throw (<anonymous>)
    at rejected (/Users/f/Sites/sister/.netlify/functions-serve/movies2/src/functions/movies2/movies2.js:3388:32)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by GV14982** [comment]
Hey there, I haven't tried running this in a Netlify function yet.

Let me see if I can find why that might be happening. I may come back here with some questions, so be on the lookout!

**Comment by cfab** [comment]
Thank you !
